name = "leansubst"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Leansubst"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Leansubst"
